package com.overseer.user.information;

public enum UserStatus {
	UNDEFINED, CREATED, ACTIVE, DISABLED_DUE_TO_INCORRECT_PASSWORD_ATTEMPTS, DISABLED_DUE_TO_INCORRECT_OTP_ATTEMPTS, DISABLED_DUE_TO_FRAUD, DISABLED_DUE_TO_INACTIVITY, DISABLED_MISC
}
